# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-05 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180905_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oreder',
            name='num',
            field=models.IntegerField(),
        ),
    ]
